### ISSUE TITLE
Investigate a config file structure that defines the order to execute workers

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#128]
Benefit is that we would not need to know in advance the order for the worker_cadence function, so we could just loop over the list.

Could be as simple as using a list of dicts:

```
All:
  - Worker1:
      Parameters:
        # ...
Linux:
  - Worker1:
      Parameters:
        # ...
  - Worker2:
      Parameters:
        # ...
Windows:
  - Worker1:
      Parameters:
        # ...
```
